/**
 * Checklist → PDF exporter (pdf-lib). Produces a clean, printable attack
 * checklist clients can approve before execution.
 */
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

interface ExportItem {
  category: string;
  technique: string;
  description: string;
  payload: string;
  status: string;
  source: string;
  ep: string;
}

const STATUS_MARK: Record<string, string> = {
  untested: '[ ]',
  tested: '[~]',
  succeeded: '[x]',
  failed: '[!]',
  blocked: '[-]',
};

// WinAnsi-safe text: Helvetica (built into pdf-lib) cannot encode many
// Unicode chars (→, ⚑, ✓…). Map the common ones, drop the rest.
const WINANSI_OK = new Set([
  0x2013, 0x2014, 0x2018, 0x2019, 0x201a, 0x201c, 0x201d, 0x201e,
  0x2020, 0x2021, 0x2022, 0x2026, 0x2030, 0x2039, 0x203a, 0x20ac, 0x2122,
]);
const CHAR_MAP: Record<number, string> = {
  0x2192: '->', 0x2190: '<-', 0x2691: '*', 0x2713: 'OK', 0x2717: 'X',
  0x2714: 'OK', 0x25b8: '>', 0x25b6: '>', 0x25c0: '<', 0x2611: 'OK',
  0x00a0: ' ',
};

function winAnsiSafe(text: string): string {
  let out = '';
  for (const ch of text) {
    const code = ch.codePointAt(0)!;
    if (code <= 0xff || WINANSI_OK.has(code)) {
      out += ch;
    } else if (CHAR_MAP[code] !== undefined) {
      out += CHAR_MAP[code];
    } else {
      out += '?';
    }
  }
  return out;
}

export async function exportChecklistPdf(
  title: string,
  code: string,
  items: ExportItem[],
): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const pageSize = { w: 595.28, h: 841.89 }; // A4 portrait
  const margin = 48;
  const lineH = 13;

  let page = doc.addPage([pageSize.w, pageSize.h]);
  let y = pageSize.h - margin;

  const header = (size: number, text: string, f: typeof font, color = rgb(0.12, 0.12, 0.14)) => {
    page.drawText(winAnsiSafe(text), { x: margin, y, size, font: f, color });
    y -= size + 8;
  };

  const ensureSpace = (needed: number) => {
    if (y - needed < margin) {
      page = doc.addPage([pageSize.w, pageSize.h]);
      y = pageSize.h - margin;
    }
  };

  const wrap = (text: string, width: number, f: typeof font, size: number): string[] => {
    const clean = winAnsiSafe(text);
    const words = clean.split(/\s+/);
    const out: string[] = [];
    let line = '';
    for (const w of words) {
      const candidate = line ? `${line} ${w}` : w;
      if (f.widthOfTextAtSize(candidate, size) <= width) {
        line = candidate;
      } else {
        if (line) out.push(line);
        line = w;
      }
    }
    if (line) out.push(line);
    return out;
  };

  // ── Title block ────────────────────────────────────────────────────────────
  header(17, title, bold);
  if (code) header(10, `Project code: ${code} · Generated by Aegis — Burp Bridge`, font, rgb(0.45, 0.45, 0.48));
  header(10, 'Items auto-mark tested when the payload appears in captured traffic, or Repeater/Intruder activity hits the endpoint.', font, rgb(0.45, 0.45, 0.48));
  y -= 6;

  if (items.length === 0) {
    header(12, 'No checklist items yet.', font);
  }

  const bodyWidth = pageSize.w - margin * 2;
  let currentCat = '';

  for (const it of items) {
    if (it.category !== currentCat) {
      currentCat = it.category;
      ensureSpace(40);
      y -= 8;
      header(13, it.category, bold);
    }

    const mark = STATUS_MARK[it.status] || '[ ]';
    const headText = `${mark}  ${it.technique}${it.ep ? `  —  ${it.ep}` : ''}`;
    const headLines = wrap(headText, bodyWidth - 14, font, 10);
    ensureSpace(headLines.length * lineH + 12);
    for (const hl of headLines) {
      page.drawText(hl, { x: margin, y, size: 10, font: it.status === 'failed' ? bold : font, color: it.status === 'failed' ? rgb(0.75, 0.15, 0.1) : rgb(0.12, 0.12, 0.14) });
      y -= lineH;
    }
    if (it.description) {
      for (const dl of wrap(it.description, bodyWidth - 14, font, 9).slice(0, 4)) {
        ensureSpace(lineH);
        page.drawText(dl, { x: margin + 14, y, size: 9, font, color: rgb(0.35, 0.35, 0.38) });
        y -= lineH - 1;
      }
    }
    if (it.payload) {
      ensureSpace(lineH);
      page.drawText(winAnsiSafe(`payload: ${it.payload}`), { x: margin + 14, y, size: 8.5, font, color: rgb(0.2, 0.35, 0.55) });
      y -= lineH - 1;
    }
    y -= 3;
  }

  const bytes = await doc.save();
  return bytes;
}
