import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { getSession } from '@/lib/auth';
import { categoryLabel } from '@/lib/cheatsheet';

export const dynamic = 'force-dynamic';

/**
 * GET /api/projects/:id/burp/checklist/export?format=markdown|pdf
 * Exports the attack checklist (for client approval / test plan docs).
 */
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const session = await getSession();
    if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const { id } = await params;
    const format = request.nextUrl.searchParams.get('format') || 'markdown';

    const project = await db.project.findUnique({
      where: { id },
      select: { id: true, name: true, engagement: true, code: true },
    });
    if (!project) return NextResponse.json({ error: 'Project not found' }, { status: 404 });

    const rows = await db.$queryRawUnsafe<Array<Record<string, unknown>>>(
      `SELECT ci.category, ci.technique, ci.description, ci.payload, ci.status, ci.source,
              e.method AS "epMethod", e.host AS "epHost", e.path AS "epPath"
       FROM "BurpChecklistItem" ci
       LEFT JOIN "BurpEndpoint" e ON e.id = ci."endpointId"
       WHERE ci."projectId" = $1
       ORDER BY ci.category ASC, ci."order" ASC, ci."createdAt" ASC`,
      id,
    );

    const items = rows.map(r => ({
      category: String(r.category),
      technique: String(r.technique || ''),
      description: String(r.description || ''),
      payload: String(r.payload || ''),
      status: String(r.status || 'untested'),
      source: String(r.source || 'ai'),
      ep: r.epHost && r.epPath ? `${r.epMethod} ${r.epHost}${r.epPath}` : '',
    }));

    const title = `Attack Checklist — ${project.name}${project.engagement ? ` (${project.engagement})` : ''}`;

    if (format === 'pdf') {
      const { exportChecklistPdf } = await import('@/lib/pdf-checklist');
      const pdf = await exportChecklistPdf(title, project.code, items);
      return new NextResponse(pdf as unknown as BodyInit, {
        headers: {
          'Content-Type': 'application/pdf',
          'Content-Disposition': `attachment; filename="aegis-checklist-${project.code || id}.pdf"`,
        },
      });
    }

    // Markdown
    const lines: string[] = [`# ${title}`, '', 'Generated by Aegis — Burp Bridge. Items are auto-marked **tested** when the payload appears in captured traffic or Repeater/Intruder activity hits the endpoint.', ''];
    let currentCat = '';
    for (const it of items) {
      if (it.category !== currentCat) {
        currentCat = it.category;
        lines.push(`## ${categoryLabel(currentCat)}`, '');
      }
      const box = it.status === 'succeeded' ? '[x]' : it.status === 'tested' ? '[~]' : it.status === 'failed' ? '[!]' : '[ ]';
      lines.push(`- ${box} **${it.technique}**${it.ep ? ` — \`${it.ep}\`` : ''}${it.status !== 'untested' ? ` _(status: ${it.status})_` : ''}`);
      if (it.description) lines.push(`  ${it.description}`);
      if (it.payload) lines.push(`  Payload: \`${it.payload}\``);
      lines.push('');
    }
    if (items.length === 0) lines.push('_No checklist items yet._', '');
    const md = lines.join('\n');

    return new NextResponse(md, {
      headers: {
        'Content-Type': 'text/markdown; charset=utf-8',
        'Content-Disposition': `attachment; filename="aegis-checklist-${project.code || id}.md"`,
      },
    });
  } catch (error) {
    console.error('[GET /api/projects/[id]/burp/checklist/export]', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
